version: 1.2.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
  - path: 'AcarsSetup\**\*.msi'
deploy:
  release: Acars-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: <your encrypted token> # your encrypted token from GitHub
  artifact: AcarsSetup\**\*.msi    # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only